apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ${postgres_user}
  POSTGRES_PASSWORD: ${postgres_password}
  POSTGRES_DB: ${postgres_db}
  POSTGRES_NON_ROOT_USER: ${postgres_non_root_user}
  POSTGRES_NON_ROOT_PASSWORD: ${postgres_non_root_password}